name: security-scanner
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - name: scan-run
        run: |
          sleep 5s
          echo "running audit"
          exit 1
